### ISSUE TITLE
Stablediffusion Livebook fails compiling XLA 0.4.4

### ISSUE THREAD

**Issue by derheap** [elixir-nx/bumblebee#171]
The Livebook "Stable Diffusion" fails during the setup with this error:

~~~~
==> exla
could not compile dependency :exla, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile exla", update it with "mix deps.update exla" or clean it with "mix deps.clean exla"


** (RuntimeError) could not find v0.4.4 release under https://github.com/elixir-nx/xla/releases
    (xla 0.4.4) lib/xla.ex:180: XLA.download_matching!/1
    (xla 0.4.4) lib/xla.ex:33: XLA.archive_path!/0
    /Users/tobias/Library/Caches/mix/installs/elixir-1.14.0-erts-13.0.3/56716fd99e60b0253cf1a2686ac47a10/deps/exla/mix.exs:106: EXLA.MixProject.extract_xla/1
    (mix 1.14.0) lib/mix/task.ex:492: Mix.Task.run_alias/6
    (mix 1.14.0) lib/mix/tasks/compile.all.ex:92: Mix.Tasks.Compile.All.run_compiler/2
    (mix 1.14.0) lib/mix/tasks/compile.all.ex:72: Mix.Tasks.Compile.All.compile/4
    (mix 1.14.0) lib/mix/tasks/compile.all.ex:59: Mix.Tasks.Compile.All.with_logger_app/2
    /Users/tobias/job/hs-flensburg/2023-Sommer/CMS/_demo/KFT-faker/stablediffusion.livemd#cell:setup:1: (file)
~~~~

Which is kind of strange, because there is a 0.4.4 release on <https://github.com/elixir-nx/xla/releases>

**Comment by jonatanklosko** [comment]
Could've been a temporary error on GitHub side, so that looking for the release file failed :)
