### ISSUE TITLE
Bumblebee.Text.TextEmbedding output_pool crashes

### ISSUE THREAD

**Issue by SteffenDE** [elixir-nx/bumblebee#216]
Hi there,

I'm trying to use the new TextEmbedding serving. It works fine without the output_pool option, but when setting it, it crashes:

```elixir
Mix.install([
  {:bumblebee, github: "elixir-nx/bumblebee", ref: "23de64b1b88ed3aad266025c207f255312b80ba6"},
  {:nx, "~> 0.5.3"},
  {:exla, "~> 0.5.3"},
  {:kino, "~> 0.9"}
])

Nx.global_default_backend(EXLA.Backend)
Nx.Defn.global_default_options(compiler: EXLA, client: :host)

model_name = "sentence-transformers/all-MiniLM-L6-v2"
{:ok, model_info} = Bumblebee.load_model({:hf, model_name})
{:ok, tokenizer} = Bumblebee.load_tokenizer({:hf, model_name})

serving =
  Bumblebee.Text.TextEmbedding.text_embedding(model_info, tokenizer,
    compile: [batch_size: 32, sequence_length: 8],
    defn_options: [compiler: EXLA],
    output_pool: :mean_pooling
  )

Kino.start_child({Nx.Serving, serving: serving, name: MyServing})
```

results in

```elixir
{:error,
 {:shutdown,
  {:failed_to_start_child, Nx.Serving,
   {%ArgumentError{message: "cannot broadcast tensor of dimensions {32, 384} to {32, 8, 1}"},
    [
      {Nx.Shape, :binary_broadcast, 4, [file: 'lib/nx/shape.ex', line: 335]},
      {Nx, :element_wise_bin_op, 4, [file: 'lib/nx.ex', line: 3570]},
      {Bumblebee.Text.TextEmbedding, :"-text_embedding/3-fun-0-", 6,
       [file: 'lib/bumblebee/text/text_embedding.ex', line: 53]},
      {Nx.Defn.Compiler, :runtime_fun, 3, [file: 'lib/nx/defn/compiler.ex', line: 158]},
      {EXLA.Defn, :"-compile/8-fun-3-", 4, [file: 'lib/exla/defn.ex', line: 385]},
      {EXLA.Defn.LockedCache, :run, 2, [file: 'lib/exla/defn/locked_cache.ex', line: 36]},
      {:timer, :tc, 1, [file: 'timer.erl', line: 235]},
      {EXLA.Defn, :compile, 8, [file: 'lib/exla/defn.ex', line: 383]}
    ]}}}}
```

I also noticed that it does not crash if I omit the compile option, but instead fails when trying to run a batch with more than one entry:

```elixir
serving =
  Bumblebee.Text.TextEmbedding.text_embedding(model_info, tokenizer,
    defn_options: [compiler: EXLA],
    output_pool: :mean_pooling
  )
```

Then:

```elixir
Nx.Serving.batched_run(MyServing, ["this is a test"])
[
  %{
    embedding: #Nx.Tensor<
      f32[384]
      EXLA.Backend<host:0, 0.768917354.493486100.226153>
      [0.044166047126054764, 0.04502343758940697, -0.04620889201760292, 0.013501535169780254, -0.0877964198589325, -0.04083893075585365, 0.010971647687256336, 0.02990402840077877, -0.03600452467799187, 0.032848503440618515, -0.06858239322900772, 0.03550782427191734, 0.010921932756900787, -0.020120518282055855, -0.06590739637613297, 0.054268475621938705, 0.07167309522628784, 0.016428733244538307, -0.04144468531012535, 0.07588311284780502, -0.044915374368429184, -0.02180401235818863, 0.03441217914223671, -0.02800421230494976, -7.485233363695443e-4, 0.12969499826431274, -0.004602501168847084, -0.01965058036148548, 0.07940661907196045, 0.10308767110109329, 0.10048440843820572, 0.0047196936793625355, -0.09783031791448593, 0.021221719682216644, -0.035896167159080505, -0.034362565726041794, -0.06834866851568222, 0.09021809697151184, -0.06440069526433945, -0.015057981945574284, 0.022991912439465523, 0.0020887625869363546, -0.07746920734643936, 0.03653478994965553, 0.007469407748430967, 0.021465329453349113, -0.08161444216966629, -8.338697371073067e-4, ...]
    >
  }
]
```

```elixir
Nx.Serving.batched_run(MyServing, ["this is a test", "this is another test"])
12:27:24.107 [error] Task #PID<0.3485.0> started from MyServing terminating
** (ArgumentError) cannot broadcast tensor of dimensions {2, 384} to {2, 128, 1}
    (nx 0.5.3) lib/nx/shape.ex:335: Nx.Shape.binary_broadcast/4
    (nx 0.5.3) lib/nx.ex:3570: Nx.element_wise_bin_op/4
    (bumblebee 0.3.0) lib/bumblebee/text/text_embedding.ex:53: anonymous fn/6 in Bumblebee.Text.TextEmbedding.text_embedding/3
    (nx 0.5.3) lib/nx/defn/compiler.ex:158: Nx.Defn.Compiler.runtime_fun/3
    (exla 0.5.3) lib/exla/defn.ex:385: anonymous fn/4 in EXLA.Defn.compile/8
    (exla 0.5.3) lib/exla/defn/locked_cache.ex:36: EXLA.Defn.LockedCache.run/2
    (stdlib 4.3.1.1) timer.erl:235: :timer.tc/1
    (exla 0.5.3) lib/exla/defn.ex:383: EXLA.Defn.compile/8
Function: #Function<14.1903805/0 in Nx.Serving.server_task_or_enqueue/3>
    Args: []
```

**Comment by SteffenDE** [comment]
Funny enough, I just realized this on my own when playing in Livebook re-implementing the serving from scratch and wanted to come here to mention this. Thanks for the awesome work you're doing!
